# Generated by Django 6.0.1 on 2026-01-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Гарчиг')),
                ('content', models.TextField(verbose_name='Агуулга')),
                ('author', models.CharField(max_length=100, verbose_name='Зохиогч')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Үзэлт')),
                ('published', models.BooleanField(default=False, verbose_name='Нийтэлсэн')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн')),
            ],
        ),
    ]
