# Generated by Django 6.0.1 on 2026-02-02 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='test',
            new_name='text',
        ),
    ]
