# Generated by Django 6.0.2 on 2026-02-04 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Нэр')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Тайлбар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ангилал',
                'verbose_name_plural': 'Ангилалууд',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Гарчиг')),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(verbose_name='Агуулга')),
                ('excerpt', models.TextField(blank=True, max_length=300, verbose_name='Товч')),
                ('featured_image', models.URLField(blank=True, verbose_name='Зураг URL')),
                ('status', models.CharField(choices=[('draft', 'Ноорог'), ('published', 'Нийтлэгдсэн')], default='draft', max_length=10, verbose_name='Төлөв')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Үзсэн тоо')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Зохиогч')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.category', verbose_name='Ангилал')),
            ],
            options={
                'verbose_name': 'Нийтлэл',
                'verbose_name_plural': 'Нийтлэлүүд',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Нэр')),
                ('author_email', models.EmailField(max_length=254, verbose_name='Имэйл')),
                ('content', models.TextField(verbose_name='Сэтгэгдэл')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Батлагдсан')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.post')),
            ],
            options={
                'verbose_name': 'Сэтгэгдэл',
                'verbose_name_plural': 'Сэтгэгдлүүд',
                'ordering': ['-created_at'],
            },
        ),
    ]
